app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */
//Permissões ADMIN
Entrust::routeNeedsRole('admin/usuarios*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/setores*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/coordenacoes*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/fornecedores*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/subitens*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/unidades*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/materiais*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/submateriais*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/relatorios*', 'admin', Redirect::to('/auth/login'));

//Permissões ADMIN, ALMOXARIFE e SOLICITANTE
Entrust::routeNeedsRole('redefinir-senha', array('admin', 'almoxarife', 'solicitante'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('update-senha', array('admin', 'almoxarife', 'solicitante'), Redirect::to('/auth/login'), false);

//Permissões ADMIN e ALMOXARIFE
Entrust::routeNeedsRole('admin', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/empenhos*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/entradas*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/pedidos*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/saidas*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);

//Permissões SOLICITANTE
Entrust::routeNeedsRole('pedidos*', 'solicitante', Redirect::to('/auth/login'));

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::group(['prefix' => 'admin'], function () {
//    Route::get('/importacao', ['as' => 'admin.importacao', 'uses' => 'ImportacaoController@importData']);
    Route::resource('usuarios', 'UsuarioController');
    Route::resource('setores', 'SetorController');
    Route::resource('coordenacoes', 'CoordenacaoController');
    Route::resource('unidades', 'UnidadeController');
    Route::resource('fornecedores', 'FornecedorController');
    Route::resource('empenhos', 'EmpenhoController');
    Route::resource('empenhos.entradas', 'EntradaController');
    Route::get('/entradas', ['as' => 'admin.entradas', 'uses' => 'EntradaController@index']);
    Route::resource('saidas', 'SaidaController');
    Route::resource('saidas.devolucoes', 'DevolucaoController');
    Route::get('/devolucoes', ['as' => 'admin.devolucoes', 'uses' => 'DevolucaoController@index']);
    Route::get('/pedidos', ['as' => 'admin.pedidos.index', 'uses' => 'PedidoController@index']);
    Route::get('/pedidos/{id}', ['as' => 'admin.pedidos.show', 'uses' => 'PedidoController@show']);
    Route::resource('materiais', 'MaterialController');
    Route::resource('subitens', 'SubItemController');
    Route::resource('submateriais', 'SubMaterialController');
    Route::get('/home', 'HomeController@index');
    Route::get('/relatorios', 'RelatorioController@index');
    Route::get('/relatorios/contabil', ['as' => 'admin.relatorios.contabil', 'uses' => 'RelatorioController@getRelatorioContabil']);
    Route::get('/relatorios/entradas-nf', ['as' => 'admin.relatorios.entradas-nf', 'uses' => 'RelatorioController@getRelatorioEntradas']);
    Route::get('/relatorios/entradas-materiais', ['as' => 'admin.relatorios.entradas-materiais', 'uses' => 'RelatorioController@getRelatorioEntradasMateriais']);
    Route::get('/relatorios/saidas-materiais', ['as' => 'admin.relatorios.saidas-materiais', 'uses' => 'RelatorioController@getRelatorioSaidasMateriais']);
    Route::get('/relatorios/empenhos', ['as' => 'admin.relatorios.empenhos', 'uses' => 'RelatorioController@getRelatorioEmpenhos']);
    Route::get('/relatorios/fornecedores', ['as' => 'admin.relatorios.fornecedores', 'uses' => 'RelatorioController@getRelatorioFornecedores']);
    Route::get('/', 'AdminController@index');
});

Route::get('/', ['as' => 'default', 'uses'=>'HomeController@index']);
Route::get('/home', 'HomeController@index');

Route::get('/ajuda', 'AjudaController@index');
Route::get('/longin-institucional', 'Auth\AuthRadiusController@authenticate');

Route::group(['prefix' => 'pedidos'], function () {
    Route::get('/', ['as' => 'pedidos', 'uses' => 'PedidoController@exibirMateriais']);
    Route::get('/busca-materiais', ['as' => 'pedidos.busca-materiais', 'uses' => 'PedidoController@search']);
    Route::get('/pedido-atual', ['as' => 'pedidos.pedido-atual', 'uses' => 'PedidoController@getPedidoAtual']);
    Route::get('/lista-pedidos', ['as' => 'pedidos.lista-pedidos', 'uses' => 'PedidoController@exibirPedidos']);
    Route::get('/consumo-do-campus', ['as' => 'pedidos.consumo-do-campus', 'uses' => 'PedidoController@getRelatorioSaidasMateriais']);
    Route::get('/{id}', ['as' => 'pedidos.show', 'uses' => 'PedidoController@show_solicitante']);
    Route::post('/add-material', ['as' => 'pedidos.add-material', 'uses' => 'PedidoController@addMaterial']);
    Route::post('/store', ['as' => 'pedidos.store', 'uses' => 'PedidoController@store']);
    Route::delete('/remover-material/{rowid}', ['as' => 'pedidos.remover-material', 'uses' => 'PedidoController@removeMaterial']);
});

Route::get('redefinir-senha', ['as' => 'redefinir-senha', 'uses' => 'UsuarioController@changePassword']);
Route::post('update-senha', ['as' => 'update-senha', 'uses' => 'UsuarioController@updatePassword']);

Route::get('form-material', ['uses' => 'EmpenhoController@getFormMaterial']);
Route::get('get-meses-relatorio/{ano}', ['uses' => 'RelatorioController@getMesesRelatorio']);
Route::get('add-material-saida/{material}/{qtd}', ['uses' => 'SaidaController@addMaterial']);

app/Pedido.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pedido extends Model {

    //
    protected $fillable = [
        'obs',
        'status'
    ];

    public function solicitante() {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function materiais() {
        return $this->belongsToMany('App\Material', 'pedido_material')->withTimestamps()->withPivot('quant');
    }
    
    public function saida(){
        return $this->hasOne('App\Saida');
    }

}

app/Http/Controllers/PedidoController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Http\Requests;
use App\Http\Controllers\Controller;
Use App\progest\repositories\PedidoRepository;
Use App\progest\repositories\MaterialRepository;
Use App\progest\repositories\CoordenacaoRepository;
Use App\progest\repositories\SetorRepository;
Use App\progest\repositories\UsuarioRepository;
Use App\progest\repositories\SaidaRepository;
use App\progest\presenters\SaidaPresenter;
Use Cart;
use Illuminate\Http\Request;
use App\Http\Requests\PedidoRequest;

class PedidoController extends Controller {

    protected $pedidoRepository;
    protected $materialRepository;
    protected $coordenacaoRepository;
    protected $setorRepository;
    protected $usuarioRepository;
    protected $saidaRepository;

    public function __construct(PedidoRepository $pedidoRepository, MaterialRepository $materialRepository, 
            CoordenacaoRepository $coordenacaoRepository, SetorRepository $setorRepository, UsuarioRepository $usuarioRepository,
            SaidaRepository $saidaRepository) {
        $this->pedidoRepository = $pedidoRepository;
        $this->materialRepository = $materialRepository;
        $this->coordenacaoRepository = $coordenacaoRepository;
        $this->setorRepository = $setorRepository;
        $this->usuarioRepository = $usuarioRepository;
        $this->saidaRepository = $saidaRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index() {
        $pedidos = $this->pedidoRepository->index(['paginate' => 50]);

        return view('admin.pedidos.index')->with(compact('pedidos'));
    }

    public function exibirMateriais() {
        $materiais = $this->materialRepository->index(['disp' => 'disponivel', 'estq' => 'em_estq', 'paginate' => 20]);
        return view('frontend.home')->with(compact('materiais'));
    }

    public function exibirPedidos() {
        $pedidos = $this->pedidoRepository->index(['user_id' => Auth::user()->id, 'paginate' => 20]);
        return view('frontend.pedidos.lista-pedidos')->with(compact('pedidos'));
    }

    public function getRelatorioSaidasMateriais(Request $input) {
        $input->flash();
        $data = $input->only('dt_inicial', 'dt_final', 'solicitante_id', 'setor_id', 'coordenacao_id', 'criterio');
        $users = array();
        $users[''] = 'Todos';
        $coordenacoes = $this->coordenacaoRepository->dataForSelect();
        $setores = $this->setorRepository->dataForSelect();
        $data['paginate'] = null;
        $saidas = array_filter($data) ? $this->saidaRepository->index($data) : null;
        if ($saidas != null && $saidas->first()) {
            $criterios = [
                'setor' => 'Setor',
                'coordenacao' => 'Coordenação',
                'solicitante' => 'Solicitante',
            ];
            $periodo = [
                'dt_inicial' => $saidas->first()->present()->formatDate($data['dt_inicial']),
                'dt_final' => $saidas->first()->present()->formatDate($data['dt_final']),
            ];
            $criterioAtual = $data['criterio'];
            $total = SaidaPresenter::CalcTotal($saidas);
            $saidas = SaidaPresenter::groupBy($data['criterio'], $saidas);
        }
        return view("frontend.consumo.materiais.relatorio")->with(compact(['saidas', 'users', 'setores', 'coordenacoes', 'total', 'criterios', 'criterioAtual', 'periodo']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(PedidoRequest $request) {
        $input = $request->only('qtds', 'obs');
        $pedido = $this->pedidoRepository->store($input);
        if ($pedido) {
            Cart::destroy();
            return redirect()->route('pedidos')->with('success', 'Pedido realizado com sucesso!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id) {
        $pedido = $this->pedidoRepository->show($id);
        if ($pedido->status == 'Pendente') {
            return view('admin.pedidos.create-saida')->with(compact('pedido'));
        } else {
            return view('admin.pedidos.show')->with(compact('pedido'));
        }
    }

    public function show_solicitante($id) {
        $pedido = $this->pedidoRepository->show($id);
        return view('frontend.pedidos.show')->with(compact('pedido'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id) {
        //
    }

    public function search(Request $request) {
        $busca = $request->only('busca');
        $materiais = $this->materialRepository->index(['disp' => 'disponivel', 'estq' => 'em_estq', 'busca' => $busca['busca'], 'paginate' => 20]);
        return view('frontend.home')->with(compact('materiais', 'busca'));
    }

    public function addMaterial(Request $request) {
        $input = $request->only('qtd');
        foreach ($input['qtd'] as $id => $qtd) {
            $material = $this->materialRepository->show($id);
            Cart::add(array('id' => $id, 'qty' => $qtd, 'name' => $material->descricao, 'price' => 0));
        }

        return redirect()->back()->with('success', 'Item adicionado ao pedido!');
    }

    public function getPedidoAtual() {
        $itens = Cart::content();
        return view('frontend.pedidos.pedido-atual')->with(compact('itens'));
    }

    public function removeMaterial($rowId) {
        Cart::remove($rowId);
        return back()->with('success', 'Item removido com sucesso!');
    }

}

resources/views/admin/pedidos/create-saida.blade.php
@extends('admin.admin_template')

@section('content')

<!--Content Wrapper. Contains page content -->
<div class = "content-wrapper">
    <!--Content Header (Page header) -->
    <section class = "content-header">
        <h1>
            {!! "Pedido nº $pedido->id"  !!}
        </h1>
    </section>

    <!--Main content -->
    <section class = "content">
        <div id='response-msg'></div>
        {!! Form::open(['route' => ["admin.saidas.store"] ])!!}
        @include('admin.pedidos.form')
        <br>
        <div class="form-group">
            <div class='col-md-12'>
                {!!Form::submit('Salvar', ['class'=>'btn btn-primary pull-right'])!!}
            </div>
        </div>
        {!! Form::close()!!}

    </section><!--/.content -->
</div><!--/.content-wrapper -->
@stop

resources/views/admin/pedidos/form.blade.php
@if ($errors->any())
<div class="container-fluid">
    <ul class="alert alert-error">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<script></script>
<div class="container-fluid">

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Materiais solicitados</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Cód</th>
                                <th>Descricao</th>
                                <th>Qtd. solicitada</th>
                                <th>Qtd. disponível</th>
                                <th>Quant</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($pedido->materiais as $material)
                            <tr>
                                <td style="width: 10%">{{$material->codigo}}</td>
                                <td style="width: 70%">{{$material->descricao}}</td>
                                <td style="width: 5%">{{($material->pivot->quant)}}</td>
                                <td style="width: 5%">{{$material->present()->getQtdEstoque()}}</td>
                                <td style="width: 10%">{!!Form::number("qtds[$material->id]", null, array('class'=>'form-control', 'id' => 'qtd[$material->id]', 'required' => 'required', 'min' => '0', 'max'=>$material->present()->getQtdEstoque < $material->pivot->quant ? $material->present()->getQtdEstoque : $material->pivot->quant, $material->present()->getQtdEstoque > 0 ? '' : 'disabled'))!!}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <p><b>Justificativa:</b> {{$pedido->obs}}</p>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
    </div>
    
    {!!Form::hidden('solicitante_id', $pedido->solicitante->id);!!}
    {!!Form::hidden("pedido[$pedido->id]", "Resolvido");!!}
    <div class="row">
        <div class='form-group'>
            <div class='col-md-12'>
                {!!Form::label('obs', 'Obs', array('class'=>'control-label'))!!}
                {!!Form::textarea('obs', null, array('class'=>'form-control', 'id' => 'obs', 'required' => 'required', 'rows'=>'3'))!!}
            </div>
        </div>
    </div>
</div>

resources/views/admin/pedidos/index.blade.php
@extends('admin.admin_template')

@section('content')
<!-- Laravel DELETE plugin -->
<script>
    window.csrfToken = '<?php echo csrf_token(); ?>';
</script>
<!--Content Wrapper. Contains page content -->
<div class = "content-wrapper">
    <!--Content Header (Page header) -->
    <section class = "content-header">
        <h1>
            {!! $page_title or "Pedidos" !!}
        </h1>
        @include('template.alerts')
    </section>

    <!--Main content -->
    <section class = "content">
        <!--Your Page Content Here -->
        @if(count($pedidos) > 0)
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Solicitante</th>
                    <th>Status</th>
                    <th>Data</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach($pedidos as $pedido)
                <tr class="{!!$pedido->status == 'Pendente'? 'warning' : ''!!}">
                    <td>{!! $pedido->id !!}</td>
                    <td>{!! $pedido->solicitante->name !!}</td>
                    <td>{!! $pedido->status !!}</td>
                    <td>{!! date('d/m/Y',strtotime($pedido->created_at)) !!}</td>
                    <td width="1%" nowrap>
                        <a href="{!! route('admin.pedidos.show', $pedido->id) !!}" class="btn btn-info btn-xs">
                            <i class="fa fa-fw fa-eye"></i> visualizar
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="row">
            <div class="col-md-12 text-center">
                {!! str_replace('/?', '?', $pedidos->render()) !!}
            </div>
        </div>
        @else
        <h5 class="well">Nenhum pedido ainda cadastrado.</h5>
        @endif
    </section><!--/.content -->
</div><!--/.content-wrapper -->
@stop

resources/views/admin/pedidos/show.blade.php
@extends('admin.admin_template')

@section('content')

<!--Content Wrapper. Contains page content -->
<div class = "content-wrapper">
    <!--Content Header (Page header) -->
    <section class = "content-header">
        <h1>
            {!! $page_title or ("Pedido $pedido->id - " ) !!}
            @if($pedido->saida != null)
            <small>
                <a href="{!! route('admin.saidas.show', $pedido->saida->id) !!}">
                    Visualizar saída
                </a>
            </small>
            @endif
        </h1>
    </section>

    <!--Main content -->
    <section class = "content">
        <div class="container-fluid">
            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">Solicitante: {{$pedido->solicitante->name}} - Pedido {{$pedido->id}}</h4>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="col-md-12">
                        <p><b>Status do pedido:</b> {{$pedido->status}}</p>
                        <p><b>Data do pedido:</b> {{date('d/m/Y',strtotime($pedido->created_at))}}</p>
                        <p><b>Justificativa:</b> {{$pedido->obs}}</p>
                    </div>
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Descrição</th>
                                <th>Qtd solicitada</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($pedido->materiais as $material)
                            <tr>
                                <td style="width: 10%">{{$material->codigo}}</td>
                                <td style="width: 75%">{{$material->descricao}}</td>
                                <td style="width: 15%">{{$material->pivot->quant}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <br><br>
                    @if($pedido->saida != null)
                    <h3 class="text-center">Itens entregues</h3>
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr class="text-center">
                                <th>Código</th>
                                <th>Descrição</th>
                                <th>Qtd</th>
                                <th>Vl. unitário</th>
                                <th>Vl. total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($pedido->saida->subMateriais as $subMaterial)
                            <tr>
                                <td style="width: 10%" class="text-center">{{$subMaterial->material->codigo}}</td>
                                <td style="width: 60%" class="text-center">{{$subMaterial->material->descricao}}</td>
                                <td style="width: 5%" class="text-center">{{$subMaterial->pivot->quant}}</td>
                                <td style="width: 10%" class="text-right">{{ $subMaterial->present()->getValorUn() }}</td>
                                <td style="width: 15%" class="text-right">{{ $subMaterial->present()->formatReal($subMaterial->pivot->quant * $subMaterial->present()->getValorUnBruto) }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <td class="text-right" colspan="2"><b>Totais</b></td>
                                <td class="text-center">{{$pedido->saida->subMateriais()->count()}}</td>
                                <td></td>
                                <td class="text-right"><b>{{$pedido->saida->present()->getValorTotal()}}</b></td>
                            </tr>
                        </tfoot>
                    </table>
                    <h3 class="text-center">Observações</h3>
                    <p>{{$pedido->saida->obs}}</p>
                    @endif
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </section><!--/.content -->
</div><!--/.content-wrapper -->
@stop