app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */
//Permissões ADMIN
Entrust::routeNeedsRole('admin/usuarios*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/setores*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/coordenacoes*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/fornecedores*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/subitens*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/unidades*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/materiais*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/submateriais*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/relatorios*', 'admin', Redirect::to('/auth/login'));

//Permissões ADMIN, ALMOXARIFE e SOLICITANTE
Entrust::routeNeedsRole('redefinir-senha', array('admin', 'almoxarife', 'solicitante'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('update-senha', array('admin', 'almoxarife', 'solicitante'), Redirect::to('/auth/login'), false);

//Permissões ADMIN e ALMOXARIFE
Entrust::routeNeedsRole('admin', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/empenhos*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/entradas*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/pedidos*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/saidas*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);

//Permissões SOLICITANTE
Entrust::routeNeedsRole('pedidos*', 'solicitante', Redirect::to('/auth/login'));

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::group(['prefix' => 'admin'], function () {
//    Route::get('/importacao', ['as' => 'admin.importacao', 'uses' => 'ImportacaoController@importData']);
    Route::resource('usuarios', 'UsuarioController');
    Route::resource('setores', 'SetorController');
    Route::resource('coordenacoes', 'CoordenacaoController');
    Route::resource('unidades', 'UnidadeController');
    Route::resource('fornecedores', 'FornecedorController');
    Route::resource('empenhos', 'EmpenhoController');
    Route::resource('empenhos.entradas', 'EntradaController');
    Route::get('/entradas', ['as' => 'admin.entradas', 'uses' => 'EntradaController@index']);
    Route::resource('saidas', 'SaidaController');
    Route::resource('saidas.devolucoes', 'DevolucaoController');
    Route::get('/devolucoes', ['as' => 'admin.devolucoes', 'uses' => 'DevolucaoController@index']);
    Route::get('/pedidos', ['as' => 'admin.pedidos.index', 'uses' => 'PedidoController@index']);
    Route::get('/pedidos/{id}', ['as' => 'admin.pedidos.show', 'uses' => 'PedidoController@show']);
    Route::resource('materiais', 'MaterialController');
    Route::resource('subitens', 'SubItemController');
    Route::resource('submateriais', 'SubMaterialController');
    Route::get('/home', 'HomeController@index');
    Route::get('/relatorios', 'RelatorioController@index');
    Route::get('/relatorios/contabil', ['as' => 'admin.relatorios.contabil', 'uses' => 'RelatorioController@getRelatorioContabil']);
    Route::get('/relatorios/entradas-nf', ['as' => 'admin.relatorios.entradas-nf', 'uses' => 'RelatorioController@getRelatorioEntradas']);
    Route::get('/relatorios/entradas-materiais', ['as' => 'admin.relatorios.entradas-materiais', 'uses' => 'RelatorioController@getRelatorioEntradasMateriais']);
    Route::get('/relatorios/saidas-materiais', ['as' => 'admin.relatorios.saidas-materiais', 'uses' => 'RelatorioController@getRelatorioSaidasMateriais']);
    Route::get('/relatorios/empenhos', ['as' => 'admin.relatorios.empenhos', 'uses' => 'RelatorioController@getRelatorioEmpenhos']);
    Route::get('/relatorios/fornecedores', ['as' => 'admin.relatorios.fornecedores', 'uses' => 'RelatorioController@getRelatorioFornecedores']);
    Route::get('/', 'AdminController@index');
});

Route::get('/', ['as' => 'default', 'uses'=>'HomeController@index']);
Route::get('/home', 'HomeController@index');

Route::get('/ajuda', 'AjudaController@index');
Route::get('/longin-institucional', 'Auth\AuthRadiusController@authenticate');

Route::group(['prefix' => 'pedidos'], function () {
    Route::get('/', ['as' => 'pedidos', 'uses' => 'PedidoController@exibirMateriais']);
    Route::get('/busca-materiais', ['as' => 'pedidos.busca-materiais', 'uses' => 'PedidoController@search']);
    Route::get('/pedido-atual', ['as' => 'pedidos.pedido-atual', 'uses' => 'PedidoController@getPedidoAtual']);
    Route::get('/lista-pedidos', ['as' => 'pedidos.lista-pedidos', 'uses' => 'PedidoController@exibirPedidos']);
    Route::get('/consumo-do-campus', ['as' => 'pedidos.consumo-do-campus', 'uses' => 'PedidoController@getRelatorioSaidasMateriais']);
    Route::get('/{id}', ['as' => 'pedidos.show', 'uses' => 'PedidoController@show_solicitante']);
    Route::post('/add-material', ['as' => 'pedidos.add-material', 'uses' => 'PedidoController@addMaterial']);
    Route::post('/store', ['as' => 'pedidos.store', 'uses' => 'PedidoController@store']);
    Route::delete('/remover-material/{rowid}', ['as' => 'pedidos.remover-material', 'uses' => 'PedidoController@removeMaterial']);
});

Route::get('redefinir-senha', ['as' => 'redefinir-senha', 'uses' => 'UsuarioController@changePassword']);
Route::post('update-senha', ['as' => 'update-senha', 'uses' => 'UsuarioController@updatePassword']);

Route::get('form-material', ['uses' => 'EmpenhoController@getFormMaterial']);
Route::get('get-meses-relatorio/{ano}', ['uses' => 'RelatorioController@getMesesRelatorio']);
Route::get('add-material-saida/{material}/{qtd}', ['uses' => 'SaidaController@addMaterial']);

resources/views/template/alerts.blade.php
@if($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

@if(Session::has('success'))
<div class="alert alert-success">{{ Session::get('success') }}</div>
@endif

resources/views/template/footer.blade.php
<footer class="main-footer">
    <!-- Default to the left -->
    <strong>Copyright © 2017 <a href="http://conquista.ifba.edu.br/" target="_blank">IFBA - Campus Vitória da Conquista</a>.</strong> Todos os direitos reservados.
</footer>

resources/views/template/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{ url('/')}}" class="logo"><img class="img-fluid" src='{{asset('img/logo-horizontal.png')}}' style="max-width: 150px"></a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        @section('toogle-button')
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        @show
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @yield('menu-pedidos')
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ asset("/bower_components/admin-lte/dist/img/user.png") }}" class="user-image" alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs"> {{Auth::user()->name}} </span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ asset("/bower_components/admin-lte/dist/img/user.png") }}" class="img-circle" alt="User Image" />
                            <p>
                                {{Auth::user()->name}} 
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        @section('botoes-usuario')
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('redefinir-senha') }}" class="btn btn-default btn-flat">Alterar Senha</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url('/auth/logout') }}" class="btn btn-default btn-flat">Sair</a>
                            </div>
                        </li>
                        @show
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
<input type="hidden" id="base_url" name="base_url" value="{{ url()}}">

resources/views/template/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">GERENCIAR</li>
            <!-- Optionally, you can add icons to the links -->
            <!--<li><a href="#"><span>Setores</span></a></li>-->
            <!--            <li class="treeview">
                            <a href="#"><span>Usuários</span> <i class="fa fa-angle-left pull-right"></i></a>
                            <ul class="treeview-menu">
                                <li><a href="#">Usuários</a></li>
                                <li><a href="#">Setores</a></li>
                                <li><a href="#">Coordenações</a></li>
                            </ul>
                        </li>-->
            @if(Auth::user()->hasRole('admin'))
            <li class="treeview">
                <a href="#"><span>Cadastros</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.usuarios.index')}}?habilitado=1"><span>Usuários</span></a></li>
                    <li><a href="{{ route('admin.setores.index')}}"><span>Setores</span></a></li>
                    <li><a href="{{ route('admin.coordenacoes.index')}}"><span>Cordenações</span></a></li>
                    <li><a href="{{ route('admin.fornecedores.index')}}"><span>Fornecedores</span></a></li>
                    <li><a href="{{ route('admin.subitens.index')}}">SubItens</a></li>
                    <li><a href="{{ route('admin.unidades.index')}}">Unidades</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#"><span>Estoque</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.materiais.index')}}">Materiais</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#"><span>Relatórios</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{route('admin.relatorios.contabil')}}">Contábil</a></li>
                    <li><a href="{{route('admin.relatorios.entradas-nf')}}">Entradas NF</a></li>
                    <li><a href="{{route('admin.relatorios.entradas-materiais')}}">Entradas materiais</a></li>
                    <li><a href="{{route('admin.relatorios.saidas-materiais')}}">Saídas materiais</a></li>
                    <li><a href="{{route('admin.relatorios.empenhos')}}">Empenhos</a></li>
                    <li><a href="{{route('admin.relatorios.fornecedores')}}">Situação fornecedores</a></li>
                </ul>
            </li>
            @endif
            <li class="treeview">
                <a href="#"><span>Movimentação</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.empenhos.index')}}">Empenhos</a></li>
                    <li><a href="{{ route('admin.entradas')}}">Entradas</a></li>
                    <li><a href="{{ route('admin.pedidos.index')}}">Pedidos</a></li>
                    <li><a href="{{ route('admin.saidas.index')}}">Saídas</a></li>
                    <li><a href="{{ route('admin.devolucoes')}}">Devoluções</a></li>
                </ul>
            </li>

        </ul><!-- /.sidebar-menu 
    </section>
        <!-- /.sidebar -->
</aside>