app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */
//Permissões ADMIN
Entrust::routeNeedsRole('admin/usuarios*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/setores*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/coordenacoes*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/fornecedores*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/subitens*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/unidades*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/materiais*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/submateriais*', 'admin', Redirect::to('/auth/login'));
Entrust::routeNeedsRole('admin/relatorios*', 'admin', Redirect::to('/auth/login'));

//Permissões ADMIN, ALMOXARIFE e SOLICITANTE
Entrust::routeNeedsRole('redefinir-senha', array('admin', 'almoxarife', 'solicitante'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('update-senha', array('admin', 'almoxarife', 'solicitante'), Redirect::to('/auth/login'), false);

//Permissões ADMIN e ALMOXARIFE
Entrust::routeNeedsRole('admin', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/empenhos*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/entradas*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/pedidos*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);
Entrust::routeNeedsRole('admin/saidas*', array('admin', 'almoxarife'), Redirect::to('/auth/login'), false);

//Permissões SOLICITANTE
Entrust::routeNeedsRole('pedidos*', 'solicitante', Redirect::to('/auth/login'));

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::group(['prefix' => 'admin'], function () {
//    Route::get('/importacao', ['as' => 'admin.importacao', 'uses' => 'ImportacaoController@importData']);
    Route::resource('usuarios', 'UsuarioController');
    Route::resource('setores', 'SetorController');
    Route::resource('coordenacoes', 'CoordenacaoController');
    Route::resource('unidades', 'UnidadeController');
    Route::resource('fornecedores', 'FornecedorController');
    Route::resource('empenhos', 'EmpenhoController');
    Route::resource('empenhos.entradas', 'EntradaController');
    Route::get('/entradas', ['as' => 'admin.entradas', 'uses' => 'EntradaController@index']);
    Route::resource('saidas', 'SaidaController');
    Route::resource('saidas.devolucoes', 'DevolucaoController');
    Route::get('/devolucoes', ['as' => 'admin.devolucoes', 'uses' => 'DevolucaoController@index']);
    Route::get('/pedidos', ['as' => 'admin.pedidos.index', 'uses' => 'PedidoController@index']);
    Route::get('/pedidos/{id}', ['as' => 'admin.pedidos.show', 'uses' => 'PedidoController@show']);
    Route::resource('materiais', 'MaterialController');
    Route::resource('subitens', 'SubItemController');
    Route::resource('submateriais', 'SubMaterialController');
    Route::get('/home', 'HomeController@index');
    Route::get('/relatorios', 'RelatorioController@index');
    Route::get('/relatorios/contabil', ['as' => 'admin.relatorios.contabil', 'uses' => 'RelatorioController@getRelatorioContabil']);
    Route::get('/relatorios/entradas-nf', ['as' => 'admin.relatorios.entradas-nf', 'uses' => 'RelatorioController@getRelatorioEntradas']);
    Route::get('/relatorios/entradas-materiais', ['as' => 'admin.relatorios.entradas-materiais', 'uses' => 'RelatorioController@getRelatorioEntradasMateriais']);
    Route::get('/relatorios/saidas-materiais', ['as' => 'admin.relatorios.saidas-materiais', 'uses' => 'RelatorioController@getRelatorioSaidasMateriais']);
    Route::get('/relatorios/empenhos', ['as' => 'admin.relatorios.empenhos', 'uses' => 'RelatorioController@getRelatorioEmpenhos']);
    Route::get('/relatorios/fornecedores', ['as' => 'admin.relatorios.fornecedores', 'uses' => 'RelatorioController@getRelatorioFornecedores']);
    Route::get('/', 'AdminController@index');
});

Route::get('/', ['as' => 'default', 'uses'=>'HomeController@index']);
Route::get('/home', 'HomeController@index');

Route::get('/ajuda', 'AjudaController@index');
Route::get('/longin-institucional', 'Auth\AuthRadiusController@authenticate');

Route::group(['prefix' => 'pedidos'], function () {
    Route::get('/', ['as' => 'pedidos', 'uses' => 'PedidoController@exibirMateriais']);
    Route::get('/busca-materiais', ['as' => 'pedidos.busca-materiais', 'uses' => 'PedidoController@search']);
    Route::get('/pedido-atual', ['as' => 'pedidos.pedido-atual', 'uses' => 'PedidoController@getPedidoAtual']);
    Route::get('/lista-pedidos', ['as' => 'pedidos.lista-pedidos', 'uses' => 'PedidoController@exibirPedidos']);
    Route::get('/consumo-do-campus', ['as' => 'pedidos.consumo-do-campus', 'uses' => 'PedidoController@getRelatorioSaidasMateriais']);
    Route::get('/{id}', ['as' => 'pedidos.show', 'uses' => 'PedidoController@show_solicitante']);
    Route::post('/add-material', ['as' => 'pedidos.add-material', 'uses' => 'PedidoController@addMaterial']);
    Route::post('/store', ['as' => 'pedidos.store', 'uses' => 'PedidoController@store']);
    Route::delete('/remover-material/{rowid}', ['as' => 'pedidos.remover-material', 'uses' => 'PedidoController@removeMaterial']);
});

Route::get('redefinir-senha', ['as' => 'redefinir-senha', 'uses' => 'UsuarioController@changePassword']);
Route::post('update-senha', ['as' => 'update-senha', 'uses' => 'UsuarioController@updatePassword']);

Route::get('form-material', ['uses' => 'EmpenhoController@getFormMaterial']);
Route::get('get-meses-relatorio/{ano}', ['uses' => 'RelatorioController@getMesesRelatorio']);
Route::get('add-material-saida/{material}/{qtd}', ['uses' => 'SaidaController@addMaterial']);

resources/views/admin/subitens/create.blade.php
@extends('admin.admin_template')

@section('content')

<!--Content Wrapper. Contains page content -->
<div class = "content-wrapper">
    <!--Content Header (Page header) -->
    <section class = "content-header">
        <h1>
            {!! $page_title or "Criar subitem" !!}
            <small>{!! $page_description or null !!}</small>
        </h1>
    </section>

    <!--Main content -->
    <section class = "content">
        {!! Form::model($subitem, ['route' => 'admin.subitens.store'])!!}
        @include('admin.subitens.form')
        <div class="form-group">
            <div class='col-md-12'>
                {!!Form::submit('Salvar', ['class'=>'btn btn-primary pull-right'])!!}
            </div>
        </div>
        {!! Form::close()!!}
        
    </section><!--/.content -->
</div><!--/.content-wrapper -->
@stop

resources/views/admin/subitens/edit.blade.php
@extends('admin.admin_template')

@section('content')

<!--Content Wrapper. Contains page content -->
<div class = "content-wrapper">
    <!--Content Header (Page header) -->
    <section class = "content-header">
        <h1>
            {!! $page_title or "Editar subitem" !!}
            <small>{!! $page_description or null !!}</small>
        </h1>
    </section>

    <!--Main content -->
    <section class = "content">
        {!! Form::model($subitem, ['route' => ['admin.subitens.update', $subitem->id], 'method'=>'PUT'])!!}
        @include('admin.subitens.form')
        <div class="form-group">
            <div class='col-md-12 '>
                {!!Form::submit('Salvar', ['class'=>'btn btn-primary pull-right'])!!}
            </div>
        </div>
        {!! Form::close()!!}
        
    </section><!--/.content -->
</div><!--/.content-wrapper -->
@stop

resources/views/admin/subitens/form.blade.php
@if ($errors->any())
<div class="container-fluid">
    <ul class="alert alert-error">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="container-fluid">
    <div class="row">
        <div class='form-group'> 
            <div class='col-md-12'>
                {!!Form::label('material_consumo', 'Material de Consumo', array('class'=>'control-label'))!!}
                {!!Form::text('material_consumo', null, array('class'=>'form-control', 'id' => 'material_consumo', 'required' => 'required'))!!}
            </div>
        </div>
    </div>
    <div class="row">
        <div class='checkbox col-md-4' >
            <label>
                {!!Form::checkbox('status', null)!!} Ativado
            </label>
        </div>
    </div>
</div>

resources/views/admin/subitens/index.blade.php
@extends('admin.admin_template')

@section('content')
<!-- Laravel DELETE plugin -->
<script>
    window.csrfToken = '<?php echo csrf_token(); ?>';
</script>

<!--Content Wrapper. Contains page content -->
<div class = "content-wrapper">
    <!--Content Header (Page header) -->
    <section class = "content-header">
        <h1>
            {!! $page_title or "Subitens" !!}
            <small>{!! $page_description or null !!}</small>
        </h1>
        @include('template.alerts')
        <small><a href="{!! route('admin.subitens.create') !!}">
                <i class="fa fa-plus"></i> Novo subitem
            </a></small>
    </section>

    <!--Main content -->
    <section class = "content">
        <!--Your Page Content Here -->
        @if(count($subitens) > 0)
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Material de Consumo</th>
                    <th>Status</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach($subitens as $subitem)
                <tr>
                    <td>{!! $subitem->id !!}</td>
                    <td>{!! $subitem->material_consumo !!}</td>
                    <td>{{$subitem->status == 1 ? 'Ativado' : 'Desativado' }}</td>
                    <td width="1%" nowrap>
                        <a href="{!! route('admin.subitens.edit', $subitem->id) !!}" class="btn btn-primary btn-xs">
                            <i class="fa fa-fw fa-pencil"></i> editar
                        </a>
<!--                        <a href="{!! route('admin.subitens.destroy', $subitem->id) !!}" data-method="delete" data-confirm="Deseja remover o registro?" class="btn btn-danger btn-xs">
                            <i class="fa fa-fw fa-remove"></i> remover
                        </a>-->
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <h5 class="well">Nenhuma subitem ainda cadastrado.</h5>
        @endif
        <div class="row">
            <div class="col-md-12 text-center">
                {!! str_replace('/?', '?', $subitens->render()) !!}
            </div>
        </div>
    </section><!--/.content -->
</div><!--/.content-wrapper -->
@stop